name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag daanh432/docker-ftps-server:$(git rev-parse --short "$GITHUB_SHA")
    - name: Push the Docker image
      run: docker push daanh432/docker-ftps-server:$(git rev-parse --short "$GITHUB_SHA")
